language: node_js

node_js:
  - '10'

sudo: false

install:
  - yarn

script:
  - yarn lint
  - yarn test:coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
